#!/bin/bash

function version_to_array() {
    local IFS
    IFS="-"
    VER=($PKGVER)
}

if grep -q 'Debian GNU/Linux 9' /etc/issue.net; then
    PCMANFM="1.2.5-3"
    MOUSEPAD="0.4.0-4"
    THUNAR="1.6.11-1"
elif grep -q 'Debian GNU/Linux 10' /etc/issue.net; then
    PCMANFM="1.3.1-1"
    MOUSEPAD="0.4.1-2"
    THUNAR="1.8.4-1"
elif grep -q 'Debian GNU/Linux 11' /etc/issue.net; then
    PCMANFM="1.3.2-1"
    MOUSEPAD="0.5.2-1"
    THUNAR="4.16.8-1"
elif grep -q 'Ubuntu 22.04.1 LTS' /etc/issue.net; then
    PCMANFM="1.3.2-1"
    MOUSEPAD="0.5.8-1"
    THUNAR="4.16.10-1"
else
    exit 0
fi

apt-get update

for APP in pcmanfm mousepad thunar; do
    # versions for buster
    if [ $APP = "pcmanfm" ]; then
        #VER=$PCMANFM
        PKGVER=$PCMANFM
        version_to_array
        VER="${VER[0]}"
    elif [ $APP = "mousepad" ]; then
        #VER=$MOUSEPAD
        PKGVER=$MOUSEPAD
        version_to_array
        VER="${VER[0]}"
    elif [ $APP = "thunar" ]; then
        #VER=$THUNAR
        PKGVER=$THUNAR
        version_to_array
        VER="${VER[0]}"
    fi
    apt-get --yes build-dep $APP
    apt-get source $APP
    mkdir -p $APP-$VER/debian/patches
    echo "$APP-$VER-minios.diff" >>$APP-$VER/debian/patches/series
    cp patches/$APP-$VER-minios.diff $APP-$VER/debian/patches/
    sed -i "s/$PKGVER/$PKGVER.minios/g" $APP-$VER/debian/changelog
    cd $APP-$VER
    dpkg-buildpackage -us -uc
    cd -
done
